version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - '8000:8000'
    environment:
      DB_USER: postgres
      DB_NAME: documents
      DB_PASSWORD: superpass
      DB_HOST: postgres
      ES_HOST: elasticsearch
    volumes:
      - '.:/app'
    command:
      [
        "uvicorn",
        "app.main:app",
        "--reload",
        "--host=0.0.0.0",
        "--port=8000",
        "--proxy-headers"
      ]

  postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: documents
      POSTGRES_PASSWORD: superpass

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ingest.geoip.downloader.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
